telegram_dbt_project_final:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: postgres
      dbname: telegram_raw_data
      schema: public
